In [38]:
import numpy as np 

arr = np.array([[1, 2, 5],[4, 0, -2],[2, -10, -22]])
arr *=2
print(arr)
arr[[0, 1, 2], [0, 1, 2]] *=10
print(arr)


[[  2   4  10]
 [  8   0  -4]
 [  4 -20 -44]]
[[  20    4   10]
 [   8    0   -4]
 [   4  -20 -440]]


In [19]:
np.arange(6)



array([0, 1, 2, 3, 4, 5])

In [54]:
# String array

strs = np.array(["Khizar", "Mark", "David", "Morgan", "Daniel"])

for i in range(strs.shape[0]):
    strs[i] = "Nothing"

print(strs)



['Nothin' 'Nothin' 'Nothin' 'Nothin' 'Nothin']


In [70]:
# Boolean indexing

numbers = np.array([np.arange(3), np.arange(3), np.arange(3)])
print(numbers)

result = numbers == 2

print(result) 

#[[False False  True]
# [False False  True]
# [False False  True]]

print(numbers[result])
print(numbers[numbers==2])



[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[False False  True]
 [False False  True]
 [False False  True]]
[2 2 2]
[2 2 2]


In [66]:
a = np.array([[10, 0, 22],[2, -1, 100]])
print(a)

b = np.array([[0, 1, 2], [0,1, 2]])
print(b)

print(a[b])

[[ 10   0  22]
 [  2  -1 100]]
[[0 1 2]
 [0 1 2]]


IndexError: index 2 is out of bounds for axis 0 with size 2

In [76]:
# 3D arrays

features = np.array([[[1, 2, 3],[9, 0, 0]],[[7, 8, 9], [9, 6, 4]]])
print(features)

[[[1 2 3]
  [9 0 0]]

 [[7 8 9]
  [9 6 4]]]


In [88]:
# reshaping

column_vector = np.array([1, 2, 3])
row_vector = column_vector.reshape(column_vector.shape[0], 1)
print("Col vector : {}".format(column_vector))
print("Row vector : {}".format(row_vector))

Col vector : [1 2 3]
Row vector : [[1]
 [2]
 [3]]


In [84]:
a = np.array([[2, 3, 3], [2, 3, 4]])
print(a.shape)
print(a.reshape(3, 2))

(2, 3)
[[2 3]
 [3 2]
 [3 4]]


In [95]:
# transpose 

a = np.array([[1,2,3],[4,5,6]])
#print(a)
a = a.T
#print(a)


a = np.array([[[1,2,3],[4,5,6]],[[-1, -2, -3], [-4, -5, -6]], [[10, 11, 12],[20, 21, 22]]])
print(a)
a = a.T
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]

 [[10 11 12]
  [20 21 22]]]
[[[ 1 -1 10]
  [ 4 -4 20]]

 [[ 2 -2 11]
  [ 5 -5 21]]

 [[ 3 -3 12]
  [ 6 -6 22]]]


In [110]:
# Empty like

a = np.array([[1,1,1],[2,2,2]])
print(a)
b = np.empty_like(a)
print(b)

[[1 1 1]
 [2 2 2]]
[[1 1 1]
 [2 2 2]]


In [122]:
# Adding numbers to each row
a = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
c = np.empty_like(a)
print(c)

for i in range(a.shape[0]):
    c[i,:] = a[i,:] + b
    
print(c)

# Using broadcasting

a1 = np.array([[1,2,3],[4,5,6]])
b1 = np.array([1,2,3])
c1 = np.empty_like(a)

print(c1)
c1 = a1+b1
print(c1)

[[1 2 3]
 [4 5 6]]
[[2 4 6]
 [5 7 9]]
[[1 1 1]
 [2 2 2]]
[[2 4 6]
 [5 7 9]]
